"""Creacion ProductoMarcaTipo

Revision ID: b3aace601e3d
Revises: 8f2792de8307
Create Date: 2024-06-25 20:37:04.894942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3aace601e3d'
down_revision = '8f2792de8307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
